line-length = 88

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
select = ["I001"]

[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
force-sort-within-sections = true
lines-after-imports = 2
